### ISSUE TITLE
Population density?

### ISSUE THREAD

**Issue by geotheory** [CBDRH/covoid#17]
Very interesting work. Out of interest, do these models factor for population density and how if so?

**Comment by oizin** [comment]
Hi @geotheory. The currently implemented ODE based approaches model and incorporate averages. The outcome is the average number of infections, with possible inputs such as the average contact rate between people or age groups. So to the extent that the average contact rate relates to population density (e.g. lower density = lower contact rates) it can be incorporated. We do intend to incorporate more stochastic individual level models in the medium future that will very explicitly include population density.
- Oisin

**Comment by geotheory** [comment]
Ah thanks for clarifying. You may wish to look at _population-weighted density_ instead of conventional density. I'm involved in a project to create the dataset at national and top-level subnational region (e.g. geonames' ADM1). Let me know if interested.
