### ISSUE TITLE
Help me with issues found when installing this package

### ISSUE THREAD

**Issue by ZS119020074** [CBDRH/covoid#24]
# I wish you can help me with this. Since I am in China using this, there are some little bit Chinese, I hope that will not be a problem.

> devtools::install_github("cbdrh/covoid",build_vignettes = TRUE)
Downloading GitHub repo cbdrh/covoid@HEAD
√  checking for file 'C:\Users\86158\AppData\Local\Temp\Rtmpq4kWe8\remotes5bc8289b95\CBDRH-covoid-2f2aaad/DESCRIPTION' (1.3s)
-  preparing 'covoid': (6.6s)
√  checking DESCRIPTION meta-information ... 
   Warning: C:/Users/86158/AppData/Local/Temp/RtmpWQJdjs/Rbuild4da0201a2a9/covoid/man/create_intervention.Rd:38: unexpected section header '\description'
   Warning: C:/Users/86158/AppData/Local/Temp/RtmpWQJdjs/Rbuild4da0201a2a9/covoid/man/create_intervention.Rd:43: unexpected END_OF_INPUT '
   '
-  installing the package to process help pages (447ms)
E  creating vignettes (2m 7.8s)
   --- re-building 'age-structured-mixing-background.Rmd' using rmarkdown
   Scale for 'fill' is already present. Adding another scale for 'fill', which
   will replace the existing scale.
   Scale for 'fill' is already present. Adding another scale for 'fill', which
   will replace the existing scale.
   Scale for 'fill' is already present. Adding another scale for 'fill', which
   will replace the existing scale.
   Scale for 'fill' is already present. Adding another scale for 'fill', which
   will replace the existing scale.
   Warning in is.na(caption) :
     is.na()不适用于类别为'expression'的非串列或非矢量
   Warning: The vignette title specified in \VignetteIndexEntry{} is different from the title in the YAML metadata. The former is "age-structured-mixing", and the latter is "Age structured epidemic models". If that is intentional, you may set options(rmarkdown.html_vignette.check_title = FALSE) to suppress this check.
   --- finished re-building 'age-structured-mixing-background.Rmd'
   
   --- re-building 'age-structured-mixing.Rmd' using rmarkdown
   Warning: The vignette title specified in \VignetteIndexEntry{} is different from the title in the YAML metadata. The former is "age-structure-mixing", and the latter is "Age structured epidemic models in COVOID". If that is intentional, you may set options(rmarkdown.html_vignette.check_title = FALSE) to suppress this check.
   --- finished re-building 'age-structured-mixing.Rmd'
   
   --- re-building 'available-models.Rmd' using rmarkdown
   Quitting from lines 342-349 (available-models.Rmd) 
   Error: processing vignette 'available-models.Rmd' failed with diagnostics:
   Object not found 'Ece'
   --- failed re-building 'available-models.Rmd'
   
   --- re-building 'covoid-model-usage.Rmd' using rmarkdown
   Warning: The vignette title specified in \VignetteIndexEntry{} is different from the title in the YAML metadata. The former is "covoid-model-usage", and the latter is "The COVOID model". If that is intentional, you may set options(rmarkdown.html_vignette.check_title = FALSE) to suppress this check.
   --- finished re-building 'covoid-model-usage.Rmd'
   
   SUMMARY: processing the following file failed:
     'available-models.Rmd'
   
   错误: Vignette re-building failed.
   此外: Warning message:
   In tools::buildVignettes(dir = ".", tangle = TRUE) :
     Files named as vignettes but with no recognized vignette engine:
      'vignettes/dynamic-vaccination-strategies.Rmd'
      'vignettes/static-vaccination-models.Rmd'
   (Is a VignetteBuilder field missing?)
   停止执行
错误: Failed to install 'covoid' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> SUMMARY: processing the following file failed:
E>   'available-models.Rmd'
E> 
E> 错误: Vignette re-building failed.
E> 此外: Warning message:
E> In tools::buildVignettes(dir = ".", tangle = TRUE) :
E>   Files named as vignettes but with no recognized vignette engine:
E>    'vignettes/dynamic-vaccination-strategies.Rmd'
E>    'vignettes/static-vaccination-models.Rmd'
E> (Is a VignetteBuilder

**Comment by ZS119020074** [comment]
Sorry for the markdown syntax, the bullet points are actually ">"s.

**Comment by MarkHanly** [comment]
Hi,

Thank you for flagging this bug. It looks like there is an issue with one of the vignettes. We are going to follow up on this but in the meantime can you try installing the package without the vignettes:

`devtools::install_github("cbdrh/covoid", build_vignettes = FALSE)`

The vignettes can be accessed online here instead: https://cbdrh.github.io/covoidance/

All the best,
Mark

**Comment by ZS119020074** [comment]
Thank you very much! That solves my problem.

**Comment by oizin** [comment]
Using `devtools::install_github("cbdrh/covoid",build_vignettes = TRUE)` should work again

**Comment by ZS119020074** [comment]
Okay, thank you for this.
